### ISSUE TITLE
1.17.1 Not loading

### ISSUE THREAD

**Issue by HRZNzero** [MeechaPooch/Coords#2]
1.17.1 Not loading 

[11:51:29] [Server thread/ERROR]: Could not load 'plugins/coords-1.0-1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.17
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:361) ~[patched_1.16.5.jar:git-Airplane-9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.16.5.jar:git-Airplane-9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Airplane-9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Airplane-9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Airplane-9]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:272) ~[patched_1.16.5.jar:git-Airplane-9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071) ~[patched_1.16.5.jar:git-Airplane-9]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-9]
	at java.lang.Thread.run(Unknown Source) [?:?]
	

Java 16
Paperspigot 1.16.5

**Comment by HRZNzero** [comment]
Postedit since I think my title is a bit confusing:

The issue is that it says it can't load in 1.16.5 because its built for a 1.17 api

**Comment by MeechaPooch** [comment]
Which exact server jar are you using? (Version and fork -- ie spigot 1.16.5)
